[package]
name = "checksum"
description = "High-performance checksums with automatic SIMD acceleration"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[features]
default = ["std"]
std = ["alloc", "traits/std", "platform/std"]
alloc = ["traits/alloc"]
no-tables = []

[dependencies]
platform = { workspace = true } #unified
traits = { workspace = true } #unified

[dev-dependencies]
crc = "3.4.0"
crc-fast = "1.8.1"
crc32c = "0.6.8"
crc32fast = "1.5.0"
crc64fast = "1.1.0"
crc64fast-nvme = "1.2.1"
criterion = { workspace = true } #unified
proptest = { workspace = true } #unified

[[bench]]
name = "crc16"
harness = false

[[bench]]
name = "crc24"
harness = false

[[bench]]
name = "crc32"
harness = false

[[bench]]
name = "crc32c"
harness = false

[[bench]]
name = "crc64"
harness = false

[[bench]]
name = "combine"
harness = false

[[bench]]
name = "comp_bench"
harness = false

[lints]
workspace = true
