# Edition
edition = "2024"
style_edition = "2024"

# Layout
tab_spaces = 2
max_width = 120
hard_tabs = false

# Imports
reorder_imports = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Formatting
format_code_in_doc_comments = true
format_strings = true
normalize_comments = true
wrap_comments = true
comment_width = 100

# Consistency
use_field_init_shorthand = true
use_try_shorthand = true

# Strictness
error_on_line_overflow = false
error_on_unformatted = false
