[package]
name = "platform-fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4.10"
arbitrary = { version = "1.4.2", features = ["derive"] }

[dependencies.platform]
path = ".."
features = ["testing"]

# Fuzz targets

[[bin]]
name = "caps"
path = "fuzz_targets/caps.rs"
test = false
doc = false
bench = false

[[bin]]
name = "caps_ops"
path = "fuzz_targets/caps_ops.rs"
test = false
doc = false
bench = false
